<?php

/**
 *--------------------------------------
 * language set
 *--------------------------------------
 * @project		: pfa
 * @author		: cblee
 * @created		: 2012-9-23
 * @copyright	: (c)2012 AsThis
 *--------------------------------------
 */

defined('PFA_PATH') or exit('Access Denied');

return array(
	'af' => 'Afrikaans',
	'sq' => 'shqip',
	'eu' => 'euskara',
	'bg' => 'български',
	'be' => 'беларуская',
	'ca' => 'català',
	'zh' => '中文',
	'zh-cn' => '中文/中国大陆',
	'zh-tw' => '中文/台灣',
	'zh-hk' => '中文/香港',
	'zh-sg' => '中文/新加坡',
	'hr' => 'hrvatski',
	'cs' => 'čeština',
	'da' => 'dansk',
	'nl' => 'Nederlands',
	'nl-be' => 'Nederlands/België',
	'en' => 'English',
	'en-gb' => 'English/United Kingdom',
	'en-us' => 'English/United Satates',
	'en-au' => 'English/Australian',
	'en-ca' => 'English/Canada',
	'en-nz' => 'English/New Zealand',
	'en-ie' => 'English/Ireland',
	'en-za' => 'English/South Africa',
	'en-jm' => 'English/Jamaica',
	'en-bz' => 'English/Belize',
	'en-tt' => 'English/Trinidad',
	'et' => 'eesti',
	'fo' => 'føroyskt',
	'fa' => 'فارسی',
	'fi' => 'suomi',
	'fr' => 'français',
	'fr-be' => 'français/Belgique',
	'fr-fr' => 'français/France',
	'fr-ch' => 'français/Suisse',
	'fr-ca' => 'français/Canada',
	'fr-lu' => 'français/Luxembourg',
	'gd' => 'Gàidhlig',
	'gl' => 'galego',
	'de' => 'Deutsch',
	'de-at' => 'German/Österreich',
	'de-de' => 'German/Deutschland',
	'de-ch' => 'German/Schweiz',
	'de-lu' => 'German/Luxemburg',
	'de-li' => 'German/Liechtenstein',
	'el' => 'Ελληνικά',
	'hi' => 'हिन्दी',
	'hu' => 'magyar',
	'id' => 'Bahasa Indonesia',
	'in' => 'Bahasa Indonesia',
	'is' => 'íslenska',
	'ga' => 'Gaeilge',
	'it' => 'italiano',
	'it-ch' => 'Italian/Svizzera',
	'ja' => '日本語',
	'ko' => '한국어',
	'lv' => 'latviešu',
	'lt' => 'lietuvių',
	'mk' => 'македонски',
	'ms' => 'Bahasa Melayu',
	'mt' => 'Malti',
	'no' => 'norsk bokmål',
	'pl' => 'polski',
	'pt' => 'português',
	'pt-br' => 'português/Brasil',
	'rm' => 'rumantsch',
	'ro' => 'română',
	'ro-mo' => 'română/Moldova',
	'ru' => 'русский',
	'ru-mo' => 'Russian/Молдавия',
	'gd' => 'Gàidhlig',
	'sr' => 'српски',
	'sk' => 'slovenčina',
	'sl' => 'slovenščina',
	'sb' => 'Sorben',
	'es' => 'español',
	'es-do' => 'español',
	'es-ar' => 'español/Argentina',
	'es-co' => 'español/Colombia',
	'es-mx' => 'español/México',
	'es-es' => 'español/España',
	'es-gt' => 'español/Guatemala',
	'es-cr' => 'español/Costa Rica',
	'es-pa' => 'español/Panamá',
	'es-ve' => 'español/Venezuela',
	'es-pe' => 'español/Perú',
	'es-ec' => 'español/Ecuador',
	'es-cl' => 'español/Chile',
	'es-uy' => 'español/Uruguay',
	'es-py' => 'español/Paraguay',
	'es-bo' => 'español/Bolivia',
	'es-sv' => 'español/El Salvador',
	'es-hn' => 'español/Honduras',
	'es-ni' => 'español/Nicaragua',
	'es-pr' => 'español/Puerto Rico',
	'sx' => 'Sutu',
	'sv' => 'svenska',
	'sv-fi' => 'svenska/Findland',
	'ts' => 'Xitsonga',
	'tn' => 'Setswana',
	'tr' => 'Türkçe',
	'uk' => 'українська',
	'ur' => 'اردو',
	'vi' => 'Tiếng Việt',
	'xh' => 'isiXhosa',
	'ji' => 'ייִדיש',
	'zu' => 'isiZulu',
	);
?>