document.write('<object type="application/x-shockwave-flash" data="{-:*__PUBLIC__-}flash/slide.swf?xml=');
document.write('	<data>');
document.write('		<channel>');
	{-foreach:$_ASI['ad'],$ad-}
document.write('			<item>');
document.write('				<link>{-:$ad['a_link']|str_replace~'&','^',@me-}</link>');
document.write('				<image>{-if:!empty($ad['a_file'])-}{-:$ad['a_file']-}{-else:-}{-:*__APP__-}u/site/no_thumb.png{-:/if-}</image>');
document.write('				<title>{-:$ad['a_name']-}</title>');
document.write('			</item>');
	{-:/foreach-}
document.write('		</channel>');
document.write('		<config>');
document.write('			<roundCorner>5</roundCorner>');
document.write('			<autoPlayTime>5</autoPlayTime>');
document.write('			<isHeightQuality>false</isHeightQuality>');
document.write('			<blendMode>normal</blendMode>');
document.write('			<transDuration>1</transDuration>');
document.write('			<windowOpen>_self</windowOpen>');
document.write('			<btnSetMargin>auto 5 5 auto</btnSetMargin>');
document.write('			<btnDistance>20</btnDistance>');
document.write('			<titleBgColor>0x000000</titleBgColor>');
document.write('			<titleTextColor>0xffffff</titleTextColor>');
document.write('			<titleBgAlpha>0.2</titleBgAlpha>');
document.write('			<titleMoveDuration>1</titleMoveDuration>');
document.write('			<btnAlpha>.5</btnAlpha>');
document.write('			<btnTextColor>0xffffff</btnTextColor>');
document.write('			<btnDefaultColor>0x000000</btnDefaultColor>');
document.write('			<btnHoverColor>0x0066ff</btnHoverColor>');
document.write('			<btnFocusColor>0x0066ff</btnFocusColor>');
document.write('			<changImageMode>hover</changImageMode>');
document.write('			<isShowBtn>true</isShowBtn>');
document.write('			<isShowTitle>false</isShowTitle>');
document.write('			<scaleMode>noBorder</scaleMode>');
document.write('			<transform>breatheBlur</transform>');
document.write('			<isShowAbout>false</isShowAbout>');
document.write('		</config>');
document.write('	</data>');
document.write('"  width="{-:$_ASI['as_width']-}" height="{-:$_ASI['as_height']-}" id="ad_slide_{-:$_ASI['ad_space_id']-}" wmode="transparent">');
document.write('<param name="wmode" value="transparent">');
document.write('<param name="movie" value="{-:*__PUBLIC__-}flash/slide.swf?xml=');
document.write('	<data>');
document.write('		<channel>');
	{-foreach:$_ASI['ad'],$ad-}
document.write('			<item>');
document.write('				<link>{-:$ad['a_link']|str_replace~'&','^',@me-}</link>');
document.write('				<image>{-if:!empty($ad['a_file'])-}{-:$ad['a_file']-}{-else:-}{-:*__APP__-}u/site/no_thumb.png{-:/if-}</image>');
document.write('				<title>{-:$ad['a_name']-}</title>');
document.write('			</item>');
	{-:/foreach-}
document.write('		</channel>');
document.write('		<config>');
document.write('			<roundCorner>5</roundCorner>');
document.write('			<autoPlayTime>5</autoPlayTime>');
document.write('			<isHeightQuality>false</isHeightQuality>');
document.write('			<blendMode>normal</blendMode>');
document.write('			<transDuration>1</transDuration>');
document.write('			<windowOpen>_self</windowOpen>');
document.write('			<btnSetMargin>auto 5 5 auto</btnSetMargin>');
document.write('			<btnDistance>20</btnDistance>');
document.write('			<titleBgColor>0x000000</titleBgColor>');
document.write('			<titleTextColor>0xffffff</titleTextColor>');
document.write('			<titleBgAlpha>0.2</titleBgAlpha>');
document.write('			<titleMoveDuration>1</titleMoveDuration>');
document.write('			<btnAlpha>.5</btnAlpha>');
document.write('			<btnTextColor>0xffffff</btnTextColor>');
document.write('			<btnDefaultColor>0x000000</btnDefaultColor>');
document.write('			<btnHoverColor>0x0066ff</btnHoverColor>');
document.write('			<btnFocusColor>0x0066ff</btnFocusColor>');
document.write('			<changImageMode>hover</changImageMode>');
document.write('			<isShowBtn>true</isShowBtn>');
document.write('			<isShowTitle>false</isShowTitle>');
document.write('			<scaleMode>noBorder</scaleMode>');
document.write('			<transform>breatheBlur</transform>');
document.write('			<isShowAbout>false</isShowAbout>');
document.write('		</config>');
document.write('	</data>" />');
document.write('</object>');
