<?php
defined('PFA_PATH') or exit('Access Denied');

return array(
	'Ad' => L('AD_CTRLR'),
	'Admin' => L('ADMIN_CTRLR'),
	'AdminLog' => L('ADMIN_LOG_CTRLR'),
	'AdminPermission' => L('ADMIN_PERMISSION_CTRLR'),
	'AdminRole' => L('ADMIN_ROLE_CTRLR'),
	'AdSpace' => L('AD_SPACE_CTRLR'),
	'Ajax' => L('AJAX_CTRLR'),
	'ArchiveChannel' => L('ARCHIVE_CHANNEL_CTRLR'),
	'Archive' => L('ARCHIVE_CTRLR'),
	'ArchiveFlag' => L('ARCHIVE_FLAG_CTRLR'),
	'ArchiveModel' => L('ARCHIVE_MODEL_CTRLR'),
	'ArchiveReview' => L('ARCHIVE_REVIEW_CTRLR'),
	'Build' => L('BUILD_CTRLR'),
	'Common' => L('COMMON_CTRLR'),
	'CustomList' => L('CUSTOM_LIST_CTRLR'),
	'CustomModel' => L('CUSTOM_MODEL_CTRLR'),
	'Database' => L('DATABASE_CTRLR'),
	'Email' => L('EMAIL_CTRLR'),
	'Extension' => L('EXTENSION_CTRLR'),
	'Finder' => L('FINDER_CTRLR'),
	'FlinkCategory' => L('FLINK_CATEGORY_CTRLR'),
	'Flink' => L('FLINK_CTRLR'),
	'Guestbook' => L('GUESTBOOK_CTRLR'),
	'Index' => L('INDEX_CTRLR'),
	'Inlink' => L('INLINK_CTRLR'),
	'Linkage' => L('LINKAGE_CTRLR'),
	'LinkageItem' => L('LINKAGE_ITEM_CTRLR'),
	'Login' => L('LOGIN_CTRLR'),
	'Manage' => L('MANAGE_CTRLR'),
	'MemberCreditOrder' => L('MEMBER_CREDIT_ORDER_CTRLR'),
	'MemberCreditType' => L('MEMBER_CREDIT_TYPE_CTRLR'),
	'Member' => L('MEMBER_CTRLR'),
	'MemberFavorite' => L('MEMBER_FAVORITE_CTRLR'),
	'MemberLevel' => L('MEMBER_LEVEL_CTRLR'),
	'MemberModel' => L('MEMBER_MODEL_CTRLR'),
	'MemberNotify' => L('MEMBER_NOTIFY_CTRLR'),
	'MemberPermission' => L('MEMBER_PERMISSION_CTRLR'),
	'Menu' => L('MENU_CTRLR'),
	'MenuSpace' => L('MENU_SPACE_CTRLR'),
	'Option' => L('OPTION_CTRLR'),
	'Report' => L('REPORT_CTRLR'),
	'SinglePage' => L('SINGLE_PAGE_CTRLR'),
	'Tag' => L('TAG_CTRLR'),
	'Task' => L('TASK_CTRLR'),
	'Template' => L('TEMPLATE_CTRLR'),
	'Toolbox' => L('TOOLBOX_CTRLR'),
	'Upload' => L('UPLOAD_CTRLR'),
	'Vote' => L('VOTE_CTRLR'),
);
?>